### ISSUE TITLE
Error on building the lib

### ISSUE THREAD

**Issue by softwaredownload** [mxk/go-sqlite#1]
I like your go-sqite lib.

I ran "go get github.com/mxk/go-sqlite/sqlite" to install this lib, got message:

package github.com/mxk/go-sqlite/sqlite
    imports github.com/mxk/go-sqlite/sqlite
    imports github.com/mxk/go-sqlite/sqlite: cannot find package "github.com/mxk/go-sqlite/sqlite" in any of:
    D:\path\src\pkg\github.com\mxk\go-sqlite\sqlite (from $GOROOT)
    D:\pathtogolib\src\github.com\mxk\go-sqlite\sqlite (from $GOPATH)

I've built https://github.com/mattn/go-sqlite3 static lib without issue.

I'm using go 1.2.1 i386 on Windows

**Comment by mxk** [comment]
You forgot the '3' on the end: `go get github.com/mxk/go-sqlite/sqlite3`
