### ISSUE TITLE
sqlite3 encrypt API

### ISSUE THREAD

**Issue by denji** [mxk/go-sqlite#12]
SQLCipher is an open source extension to SQLite that provides transparent 256-bit AES encryption of database files.
- https://github.com/sqlcipher/sqlcipher (SQLCipher Community Edition)
#### Features
- Fast performance with as little as 5-15% overhead for encryption on many operations
- 100% of data in the database file is encrypted
- Good security practices (CBC mode, key derivation)
- Zero-configuration and application level cryptography
- Algorithms provided by the peer reviewed OpenSSL crypto library.
- Configurable crypto providers

**Comment by mxk** [comment]
I'm aware of sqlcipher. I wanted to implement authenticated encryption using Go packages, so that's what my API is aimed at. Performance is likely to be worse due to Go -> C -> Go call overhead, but I haven't compared it with sqlcipher.
