### ISSUE TITLE
call back function

### ISSUE THREAD

**Issue by seshu3564** [mxk/go-sqlite#13]
for the call back function to get called, should the update or delete operations be executed from connection itself in golang  or can they be executed from sqlite3 terminal so that i can keep program waiting for function to be called.

**Comment by seshu3564** [comment]
sorry for less details, callback function means i meant the UpdateFunc(). it is getting called fine when i used conn.execute(update stmt) on db. but when i went to terminal and executed the same update statement on db table it is not getting called. i'm keeping the connection open and making the program wait using waitgroup.

**Comment by mxk** [comment]
Callback functions will not be executed across connections. SQLite doesn't have a server that can pass information between connections.
