### ISSUE TITLE
Database Encryption

### ISSUE THREAD

**Issue by Phisatho** [mxk/go-sqlite#16]
I tried to encrypt database following Godoc (codec). My code below: 
```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/mxk/go-sqlite/sqlite3"
	"log"
	"os"
)

func main() {
	os.Remove("./foo.db")

	db, err := sql.Open("sqlite3", "./foo.db")
	if err != nil {
		log.Fatal(err)
	}
	db.Key("main", []byte("aes-hmac::secretkey1"))
	defer db.Close()
```
What am I missing?
Is it possible to post an example code?

**Comment by Phisatho** [comment]
Sorry, I forgot to mention the output.
`db.Key undefined (type *sql.DB has no field or method Key)`

**Comment by mxk** [comment]
Sorry, but this library is no longer maintained and is not compatible with the current Go release. Please use mattn's version instead.
