### ISSUE TITLE
Value or Null support

### ISSUE THREAD

**Issue by richardcrichardc** [mxk/go-sqlite#8]
Hi,

Is there any support for binding a value or Null, like can be done with NullString and similar types from database/sql in the standard library? I have inspected the code and tried a few things out but had no luck. I am using this library as it is the only Go/SQLite3 library I can find that supports SQLite BinaryIO.

Thanks,

Richard

**Comment by mxk** [comment]
Hi Richard,

Can you give me an example of what you would like to do? Any parameter that you don't bind or bind to nil will be stored as NULL.

**Comment by richardcrichardc** [comment]
Below is the code I have at the moment. I am using positional arguments. Sometimes columns can contain null. It would be great to be able to do this without separate queries.

I am just wondering if there is a way to do this that I have missed. If there is not I will just write more verbose code.

```
func AddDocument(conn *sqlite3.Conn, parentId int64, name, filename, mimeType string, fileContents []byte) {
    err := conn.Exec("INSERT INTO Documents(parentId, Name, Filename, MimeType, File) VALUES(?, ?, ?, ?, ?)", parentId, name, filename, mimeType, fileContents)
    if err != nil {
        log.Panic(err)
    }
}
```

**Comment by mxk** [comment]
Would a map work?

```
args := sqlite3.NamedArgs{"$parentId": parentId}
if name != "" {
    args["$name"] = name
}
c.Exec("INSERT INTO Documents(parentId, Name, Filename, MimeType, File) VALUES($parentId, $name, ...)", args)
```

**Comment by richardcrichardc** [comment]
It probably would.
